### PR TITLE
Add `nodeNext` and `node16` support

### LINKED ISSUE #110: There is a compatibility issue with "moduleResolution": "NodeNext" in TS
**Describe the bug**
Codemirror does not compile with typescript 4.8 when "module": "ESNext" and "moduleResolution": "NodeNext" in the tsconfig. Error:
```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("ts-pattern")' call instead.
```
In a few words, TS introduced new ways to publish and consume type definitions and TS files depending on if you code using ESM or Commonjs.

* [I believe the change was announced here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs) * [More actionable background here.](https://github.com/microsoft/TypeScript/issues/46408#issuecomment-946167806)

 [According to this](https://github.com/microsoft/TypeScript/issues/46408#issuecomment-961188448), adding an `index.d.cts` does the trick. So I copy-pasted the `index.d.ts` and renamed it. Then I removed `types` from the `package.json` and it did not work.

**Versions**
- TypeScript version: 4.8.2
- ts-pattern version: 4.0.4
- environment: browser + version / node version / deno version

### PR DESCRIPTION
**Pull request by cuppachino**
This [branch](https://github.com/Cuppachino/ts-pattern-nodenext/tree/node-next) potentially fixes #110. I used [tsup](https://github.com/egoist/tsup) to quickly try out a few common configs, but this change needs more testing.

### changes
| |  |
| - | :- |
| `jest.config.cjs` | Transform hard-coded `.js` to `.ts` during testing. |
| `package.json`| Expose `.d.ts` exports & use `tsconfig.prod.json` in scripts |
| `src/**/*.(ts\|mts\|cts)` | [regexp](https://stackoverflow.com/a/73075563/17867284) workaround. append `.js` to imports |
| `tsconfig.json` | enforce import paths end with `.js` during development |
| `tsconfig.prod.json` | extends dev config with microbundles' [recommended settings](https://github.com/developit/microbundle#using-with-typescript) |

### CODE REVIEW

**Comment by gvergnaud** [comment]
@cuppachino I didn't look at the new `bundler` resolution mode very closely, is there something we should do on the ts-pattern side, or does this new mode fix this issue for us?

**Comment by cuppachino** [comment]
@gvergnaud I just checked the [PR](https://github.com/microsoft/TypeScript/pull/51669#issue-1467004047) for it, and I think if we want to hit both module systems for both browser and node we have to use `node16` / `nodeNext`.

From a bunch of experimentation, this *seems* to be the easiest way to do it:

## Use esm by default
- set package.json type to "module".
- use `.ts` extension for source files.
- if you need a commonjs source file, use the `.cts` extension.
- import complete paths, relative to the file's dist location, specifying `.js` / `.cjs` / .mjs` extensions.

#### tsconfig.json

```json
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "target": "ES2020",
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "outDir": "./dist/esm"
  }
}
```

#### tsconfig.cjs.json

```json
{
    "compilerOptions": {
      "target": "ES2015",
      "module": "CommonJS",
      "moduleResolution": "nodenext",
      "outDir": "./dist/cjs"
    },
    "extends": "./tsconfig.base.json"
}
```

- build to `dist/esm/` using `tsconfig.json`
- build to `dist/cjs/` using `tsconfig.cjs.json`
  - run a script to replace `dist/cjs/*.js` with `.cjs` extensions.
  - (maybe not necessary) copy an `index.d.ts` from one of the output folders to the root of `dist/`
- configure package.json exports:

```json
{
  "type": "module",
  "main": "./dist/cjs/index.js",
  "module": "./dist/esm/index.js",
  "exports": {
    "types": "./dist/index.d.ts",
    "import": "./dist/esm/index.js",
    "require": "./dist/cjs/index.cjs",
    "browser": "./dist/esm/index.js",
    "default": "./dist/cjs/index.cjs"
  }
}
```

**Comment by cuppachino** [comment]
Just tried this out in another popular project with success. Here's the [conversion commit](https://github.com/cuppachino/openapi-typescript-fetch/commit/3a774f9cc4568d18d5d8cbb78de3a72bf6f42885). 

I'd suggest using microbundle on JavaScript after compilation with tsc (+ the steps previously mentioned) or not at all.

[openapi-typescript-fetch #41](https://github.com/ajaishankar/openapi-typescript-fetch/issues/41)

**Comment by gvergnaud** [comment]
closing in favor of #160
