### ISSUE TITLE
There is a compatibility issue with "moduleResolution": "NodeNext" in TS

### ISSUE THREAD

**Issue by 0xDing** [gvergnaud/ts-pattern#110]
**Describe the bug**
Codemirror does not compile with typescript 4.8 when "module": "ESNext" and "moduleResolution": "NodeNext" in the tsconfig. Error:
```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("ts-pattern")' call instead.
```
In a few words, TS introduced new ways to publish and consume type definitions and TS files depending on if you code using ESM or Commonjs.

* [I believe the change was announced here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs) * [More actionable background here.](https://github.com/microsoft/TypeScript/issues/46408#issuecomment-946167806)

 [According to this](https://github.com/microsoft/TypeScript/issues/46408#issuecomment-961188448), adding an `index.d.cts` does the trick. So I copy-pasted the `index.d.ts` and renamed it. Then I removed `types` from the `package.json` and it did not work.

**Versions**
- TypeScript version: 4.8.2
- ts-pattern version: 4.0.4
- environment: browser + version / node version / deno version

**Comment by Rawnly** [comment]
Same here, would love to find a solution 👀

**Comment by 0xDing** [comment]
> Hey! Could you provide a link to a project/repo reproducing the issue so I can take a look?

https://github.com/0xDing/ts-pattern-issue-110

**Comment by patroza** [comment]
The workaround is to remove `"type": "module"` from the package.json

**Comment by tgillus** [comment]
> For me types imported from `index.d.ts` don't work at all in my project. The workaround is to remove `"type": "module"` from the package.json.
> 
> Otherwise, the imports inside `d.ts` that is specified in the `import: { types` section of `package.json` must include `.js` module qualifiers, but I'd imagine that breaks types for cjs users. So either seems to need to drop the `type: module`, or generate separate d.ts for import vs require.
> 
> Related change: #89

Has anyone found a workaround for this issue (that doesn't require reverting back to CommonJS or modifying content within the node_modules directory)? I've been using ts-pattern 3.3.5 in order to maintain the ability to have type information (and code completion) available while coding in VSCode.

**Comment by gvergnaud** [comment]
I tried updating ts-pattern's package.json to follow [microbundle](https://github.com/developit/microbundle)'s recommendation to support NodeNext, but it doesn't seem to be working when cloning [this test repo](https://github.com/0xDing/ts-pattern-issue-110)...

Here is the PR if somebody wants to take a look: https://github.com/gvergnaud/ts-pattern/pull/136

**Comment by rhyek** [comment]
Getting `any`s everywhere with `ts-pattern@test`. 
![image](https://user-images.githubusercontent.com/702922/221701765-c4d386d9-da8a-4be7-a90a-aaea0d4dd314.png)

Hoping for a fix soon.

**Comment by jeffwad** [comment]
We've encountered the same issue working with the latest version using `.mts` in VSCode. However, one of my colleagues uses Webstorm, in which it works correctly. See screenshot of the match function showing it's type signature. 

<img width="709" alt="image (1)" src="https://user-images.githubusercontent.com/361943/225225125-456918a7-945a-4e1e-aeaa-36492e3fe4d1.png">

I don't know if this is of help - but thought you should know.

**Comment by elnygren** [comment]
Using `moduleResolution: 'bundler'` is not a fix, it just silences the issue by having a more relaxed module resolution checking. It should only be used if actually using a bundler (like webpack, esbuild, vite...). 

This project's typings are broken if using `moduleResolution: NodeNext` which is the normal moduleResolution to use if writing modern node.js with ESM (`"type": "module"` in package.json)

**Comment by viell-dev** [comment]
Checks against `arethetypeswrong`:
- v4.2.2: https://arethetypeswrong.github.io/?p=ts-pattern%404.2.2
- v4.1.4-test.0: https://arethetypeswrong.github.io/?p=ts-pattern%404.1.4-test.0

Whatever was changed in the test release is better but not perfect.

**Comment by gvergnaud** [comment]
After many iterations, I think I finally have a version that works in nodenext and + commonjs modules: 

https://arethetypeswrong.github.io/?p=ts-pattern%404.2.3

I tested it locally and it seems to be working, but It would be very helpful if you could try to install `ts-pattern@4.2.4-test.0` in your nodenext + commonjs project, and let me know if everything works as expected!
